### ISSUE TITLE
Possible inline svg issue

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [javascript-obfuscator/webpack-obfuscator#9] opened 2016-11-19 15:23 UTC
Hey,

I've been using this plugin and since 0.8.0 I've had no issues anymore up until now.
I have created a component (it's a project based on angular2) with a component template with lots of inline svg (small extract):

> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1020 1020" style="padding:2px" fill="#fff" stroke="#000" stroke-width="2" stroke-opacity="null" fill-opacity="null" stroke-linejoin="null" stroke-linecap="null">
>       
>       
>        
>       <g id="svg_lines">
>           <line x1="584.5" y1="67" x2="828.5" y2="180" id="a-to-b"/>
>           <line x1="561.5" y1="117" x2="895.5" y2="539" id="a-to-c"/>
>           <line x1="519.5" y1="140" x2="717.5" y2="865" id="a-to-d"/>
>           <line x1="473.5" y1="141" x2="286.5" y2="855" id="a-to-e" *ngIf="ePresent"/>
>           <line x1="96.5" y1="546" x2="434.5" y2="120" id="a-to-f" *ngIf="fPresent"/>
>           <line x1="169.5" y1="173" x2="414.5" y2="70" id="a-to-g" *ngIf="gPresent"/>
>           
>           <line x1="908.5" y1="331" x2="939.5" y2="519" id="b-to-c"/>
>           <line x1="845.5" y1="331" x2="763.5" y2="863" id="b-to-d"/>
>           <line x1="820.5" y1="311" x2="324.5" y2="871" id="b-to-e" *ngIf="ePresent"/>
>           <line x1="794.5" y1="267" x2="134.5" y2="578" id="b-to-f" *ngIf="fPresent"/>
>           <line x1="201.5" y1="206" x2="802.5" y2="218" id="b-to-g" *ngIf="gPresent"/>
>           
>           <line x1="916.5" y1="693" x2="801.5" y2="904" id="c-to-d"/>
>           <line x1="882.5" y1="671" x2="349.5" y2="918" id="c-to-e" *ngIf="ePresent"/>
>           <line x1="143.5" y1="626" x2="858.5" y2="628" id="c-to-f" *ngIf="fPresent"/>
>           <line x1="859.5" y1="579" x2="214.5" y2="259" id="c-to-g" *ngIf="gPresent"/>
>           
>           <line x1="649.5" y1="968" x2="352.5" y2="969" id="d-to-e" *ngIf="ePresent"/>
>           <line x1="645.5" y1="927" x2="135.5" y2="676" id="d-to-f" *ngIf="fPresent"/>
>           <line x1="187.5" y1="299" x2="676.5" y2="879" id="d-to-g" *ngIf="gPresent"/>
>           
>           <line x1="199.5" y1="896" x2="104.5" y2="711" id="e-to-f" *ngIf="ePresent && fPresent"/>
>           <line x1="236.5" y1="867" x2="147.5" y2="325" id="e-to-g" *ngIf="ePresent && gPresent"/>
>           
>           <line x1="57.5" y1="552" x2="96.5" y2="332" id="f-to-g" *ngIf="fPresent && gPresent"/>
>       </g>
>       
>       
>       
>       <text x="611.5" y="37" font-size="48" fill="#000000" [textContent]="getRightLetter('A')"></text>
>       <g>
>        <ellipse ry="65" rx="65" cy="65.404867" cx="500.305336"/>
>        
>        <ellipse ry="20" rx="19.5" cy="19.731316" cx="503.120079" [attr.fill]="base_values_color"  *ngIf="is_top_bubble"/>
>        <text y="27" x="496.5" font-size="24" *ngIf="is_top_bubble">{{counter}}</text>
>        
>        <g id="to_b">
>         <ellipse ry="20" rx="20" cy="63.977703" cx="584.502327" />
>         <ellipse ry="20" rx="20" cy="81.977703" cx="620.502327" *ngIf="!bubbleModel['is_top_bubble']"/>
>         <text font-size="24" y="72" x="578.5" >{{counter}}</text>
>         <text font-size="24" y="91" x="614.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>        <g id="to_c" transform="rotate(29.706335067749023 576.5023193359376,138.97770690917972)">
>         <ellipse ry="20" rx="20" cy="129.977703" cx="558.502327"/>
>         <ellipse ry="20" rx="20" cy="147.977703" cx="594.502327" *ngIf="!is_top_bubble"/>
>         <text font-size="24" y="138" x="552.5">{{counter}}</text>
>         <text font-size="24" y="157" x="588.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>        <g id="to_d" transform="rotate(52.62669372558594 527.5023193359375,166.97770690917966)">
>         <ellipse ry="20" rx="20" cy="157.977703" cx="509.502327"/>
>         <ellipse ry="20" rx="20" cy="175.977703" cx="545.502327" *ngIf="!is_top_bubble"/>
>         <text font-size="24" y="166" x="503.5">{{counter}}</text>
>         <text font-size="24" y="185" x="539.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>        <g id="to_e" transform="rotate(-93.02918243408203 466.5023193359375,164.97770690917974)" *ngIf="ePresent">
>         <ellipse ry="20" rx="20" cy="173.977703" cx="484.502327"/>
>         <ellipse ry="20" rx="20" cy="155.977703" cx="448.502327" *ngIf="!is_top_bubble"/>
>         <text font-size="24" y="183" x="478.5">{{counter}}</text>
>         <text font-size="24" y="164" x="442.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>        <g id="to_f" transform="rotate(-69.73283386230469 418.5023193359375,132.9777069091797)" *ngIf="fPresent">
>         <ellipse ry="20" rx="20" cy="141.977703" cx="436.502327"/>
>         <ellipse ry="20" rx="20" cy="123.977703" *ngIf="!is_top_bubble" cx="400.502327"/>
>         <text font-size="24" y="151" x="430.5">{{counter}}</text>
>         <text font-size="24" y="132" x="394.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>        <g id="to_g" transform="rotate(-48.77290725708008 399.50231933593756,79.97770690917967)" *ngIf="gPresent">
>         <ellipse ry="20" rx="20" cy="88.977703" cx="417.502327"/>
>         <ellipse ry="20" rx="20" cy="70.977703" cx="381.502327" *ngIf="!is_top_bubble"/>
>         <text font-size="24" y="98" x="411.5">{{counter}}</text>
>         <text font-size="24" y="79" x="375.5" *ngIf="!is_top_bubble">{{counter}}</text>
>        </g>
>       </g>

When I enable obfuscator for the main.js file, The !browser!tab crashes when trying to open the component.
This happens consistently on Edge and Chrome. No errormessage displayed.
When I disable obfuscator for the main.js file, I don't have any issue...

weird stuff ;-)

**Comment by sanex3339** [comment] 2016-11-19 15:30
Hi, very specific error with no message. I need demo which i can test and reproduce error. It can be only one component with this error. But this demo should be easily install from my side.

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 15:32
Ok, will do that when I have the time (can take a while, sorry, if you want I can close the issue for now).

**Comment by sanex3339** [comment] 2016-11-19 15:34
No, i won't close the issue, because the error is very interesting.

**Comment by sanex3339** [comment] 2016-11-19 15:35
But now please try to disable `selfDefending` and `debugProtection` and `domainLock` options if they are were enabled.

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 15:36
ok, give me a week or something, I hope to have met my deadline by then and be able to setup a small demo.

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 15:36
Nope, not enabled, config is:

      new JavaScriptObfuscator ({
        rotateUnicodeArray: true
      }, [
        //Also about obfuscation of `vendors` and `polyfills`. I very very very recommend to always disable obfuscation of this files because obfuscated code
        // runs about 25-30% slower and size of obfuscated files larger. So, if you will obfuscate only your (not vendor) code
        // - performance drop will haven't so noticeable affects on code performance.
        //ALL FILES PRESENT BELOW WILL NOT BE OBFUSCATED
        '**/vendor.*.js',
        '**/polyfills.*.js',
        '**/assets/**',
        '**/main.*.js'// -> lijkt issues te geven momenteel, bij versie 0.8.0? Alleen met de staticBalanceSelector? Misschien iets met svg inline?...
      ]),

**Comment by sanex3339** [comment] 2016-11-19 15:41
selfDefending is enabled by default. set it to false

**Comment by sanex3339** [comment] 2016-11-19 15:41
default options is 
```
{
    compact: true,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: true,
    reservedNames: [],
    rotateStringArray: true,
    selfDefending: true,
    sourceMap: false,
    sourceMapBaseUrl: '',
    sourceMapFileName: '',
    sourceMapMode: 'separate',
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.8,
    unicdeEscapeSequence: true
}
```

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 16:09
Ahhhh, in the end it was the:
disableConsoleOutput: false which did it.

Is it the intention that the browser tab crashes (tried in chrome, ff, edge) when something (I was outputting some objects) is logged to the console?

Seems kinda harsh.

**Comment by sanex3339** [comment] 2016-11-19 16:11
So, after you disable log of some objects crash is gone?

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 16:12
Ah that I didn’t test,

Just when setting the option: disableConsoleOutput: false the crash is gone.

 

Van: Timofey Kachalov [mailto:notifications@github.com] 
Verzonden: zaterdag 19 november 2016 17:12
Aan: javascript-obfuscator/webpack-obfuscator <webpack-obfuscator@noreply.github.com>
CC: LanderBeeuwsaert <lander.beeuwsaert@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [javascript-obfuscator/webpack-obfuscator] Possible inline svg issue (#9)

 

So, after you disable log of some objects crash is gone?

**Comment by sanex3339** [comment] 2016-11-19 16:17
Interesting.

`disableConsoleOutput` option add additional node to obfuscated code:
```
var {consoleLogDisableFunctionName} = {singleNodeCallControllerFunctionName}(this, function () {
            var getGlobal = Function('return (function() ' + '{}.constructor("return this")( )' + ');');
            
            var func = Function('for ' + '(;;)' + ' {}');
            var that = getGlobal();
                        
            that.console.log = func; 
            that.console.error = func;
            that.console.warn = func;
            that.console.info = func;
        });
        
        {consoleLogDisableFunctionName}();
```

As you can see, `console.log` and other functions is replaced by infinity loop function, so i think this is cause of the crash.

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 16:20
Haha, jep, that explains a lot.
I think it is firefox which after 20 seconds or so gives you the option to disable a script, because it is continually running, well, jep, a loop would do that ;-).

**Comment by sanex3339** [comment] 2016-11-19 16:20
So, i think in 30 mins i make patch which will replace infinity loop by empty function

**Comment by sanex3339** [comment] 2016-11-19 16:20
Because many scripts has console.log

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 16:20
ok,cool, thanks, take your time, I've disabled the option so I'm ok for now...

**Comment by LanderBeeuwsaert** [comment] 2016-11-19 16:21
Do I close? Or do you close later?

**Comment by sanex3339** [comment] 2016-11-19 16:22
I will close later after patch release

**Comment by sanex3339** [comment] 2016-11-19 17:03
Check `webpack-obfuscator@0.8.1`

**Closed** 2017-01-08 15:25 UTC
