### ISSUE TITLE
externals library can't be found

### ISSUE THREAD

**Issue by yzhang921** [javascript-obfuscator/webpack-obfuscator#47] opened 2019-01-05 05:34 UTC
Hi, I am using webpack-obfuscator to protect one of my js libraries that build by webpack.  There are some external library defined in my webpack configuration. And this library will be import or include in web pages when dev other applications. 
The problem is that all the external library cannot be found after code obfuscated.  Could you help, please?

```javascript
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const JavaScriptObfuscator = require('webpack-obfuscator');


export default (env) => {
    // console.log("===============>", env.production);
    let mode, devtool;
    if (env.production) {
        mode = 'production';
        devtool = 'none';
    } else {
        mode = 'development';
        devtool = 'cheap-module-eval-source-map';
    }

    console.log(`mode: ${mode}; devtool: ${devtool}`);

    return [
        {
            entry: {
                'dataLibary': './src/index.js',
            },
            output: {
                path: path.resolve(__dirname, './dist'),
                filename: '[name].js',
                libraryTarget: 'umd',
                globalObject: 'this',
                // libraryExport: 'default',
                library: 'dataLibary'
            },
            mode,
            devtool,
            externals: [
                {
                    'lodash': {
                        commonjs: 'lodash',
                        commonjs2: 'lodash',
                        amd: 'lodash',
                        root: '_'
                    },
                    moment: 'moment',
                    numbro: 'numbro',
                },
                'object-hash'
            ],
            module: {
                rules: [
                    {
                        test: /\.(js)$/,
                        exclude: /(node_modules|bower_components)/,
                        use: 'babel-loader'
                    }
                ]
            },
            optimization: {
                minimizer: [
                    new UglifyJSPlugin({
                        uglifyOptions: {
                            mangle: {
                                toplevel: true,
                            },
                            toplevel: true,
                        }
                    }),
                ]
            },
            plugins: [
                new CleanWebpackPlugin('dist'),
                new JavaScriptObfuscator({
                    rotateUnicodeArray: true,
                    target: 'node'
                }),
            ]
        }
    ]
};
```

**Comment by Karolusrex** [comment] 2019-11-28 12:08
I have the same problem. I think I will work around it for now (skip obfuscation), but would love to see pointers on what the cause and solution of the problem might be

**Comment by niccolomineo** [comment] 2019-12-09 07:29
Any luck?

**Comment by zamotkin** [comment] 2019-12-11 19:42
@yzhang921 It's hard to say. You are trying to use two obfuscation packages: UglifyJSPlugin and JavaScriptObfuscator. Did you try to turn off UglifyJSPlugin?

**Comment by yzhang921** [comment] 2019-12-12 08:50
Sorry, It's really too long to remember full context. I checked my project and looks like my workaround is add reservedStrings parameter.
```JavaScript
new JavaScriptObfuscator({
reservedStrings: ['lodash', 'moment', 'object-hash', 'numbro',],
...
})
```

**Comment by sanex3339** [comment] 2020-05-29 22:06
Closed as old. Fell free to create a new issue.

**Closed by sanex3339** 2020-05-29 22:06 UTC
Labels: bug
